### PR TITLE
make PGI compiler work

### PR DESCRIPTION
**Pull request by hokru**
* Adds pragma and compile flag for PGI 18.4 to make it compile.

How can I best test if all is ok and if the pragma works?

edit:

 * `python setup.py install -DCMAKE_C_COMPILER=pgcc` to build
 * `gau2grid.test()` passes all test (115 passed in 2.72 seconds)

### CODE REVIEW

**Comment by loriab** [comment]
Are you looking for basic tests? You can test the python interface https://github.com/psi4/psi4meta/blob/master/conda-recipes/gau2grid-multiout/meta.yaml#L93

**Comment by dgasmith** [comment]
`python setup.py build -DCMAKE_C_COMPILER=pgi` should get you a Python testable build.

**Comment by dgasmith** [comment]
@hokru Any luck testing this out?

**Comment by hokru** [comment]
The `gau2grid.test()` passes as edited into the OP.

**Comment by dgasmith** [comment]
@hokru Thanks! Make sure to ping me when you edit the OP as edits do not send notifications.

**Pull request merged**
